export default [
  {
    name: 'London',
    local_names: {
      et: 'London',
      kw: 'Loundres',
      uk: 'Лондон',
      sl: 'London',
      ay: 'London',
      bg: 'Лондон',
      se: 'London',
      eu: 'Londres',
      li: 'Londe',
      tg: 'Лондон',
      sa: 'लन्डन्',
      na: 'London',
      uz: 'London',
      km: 'ឡុងដ៍',
      gd: 'Lunnainn',
      tr: 'Londra',
      tl: 'Londres',
      pl: 'Londyn',
      lv: 'Londona',
      tw: 'London',
      sn: 'London',
      fr: 'Londres',
      en: 'London',
      cu: 'Лондонъ',
      wa: 'Londe',
      hu: 'London',
      af: 'Londen',
      kk: 'Лондон',
      mi: 'Rānana',
      yo: 'Lọndọnu',
      el: 'Λονδίνο',
      to: 'Lonitoni',
      mt: 'Londra',
      cs: 'Londýn',
      fo: 'London',
      fj: 'Lodoni',
      ja: 'ロンドン',
      av: 'Лондон',
      ia: 'London',
      ky: 'Лондон',
      oc: 'Londres',
      hr: 'London',
      mr: 'लंडन',
      ee: 'London',
      fy: 'Londen',
      ln: 'Lóndɛlɛ',
      feature_name: 'London',
      th: 'ลอนดอน',
      bn: 'লন্ডন',
      ne: 'लन्डन',
      gn: 'Lóndyre',
      ba: 'Лондон',
      nn: 'London',
      my: 'လန်ဒန်မြို့',
      os: 'Лондон',
      sr: 'Лондон',
      ku: 'London',
      vo: 'London',
      br: 'Londrez',
      ps: 'لندن',
      es: 'Londres',
      ta: 'இலண்டன்',
      da: 'London',
      zh: '伦敦',
      ie: 'London',
      ro: 'Londra',
      sm: 'Lonetona',
      de: 'London',
      fa: 'لندن',
      lt: 'Londonas',
      ca: 'Londres',
      kl: 'London',
      lb: 'London',
      ur: 'علاقہ لندن',
      mn: 'Лондон',
      or: 'ଲଣ୍ଡନ',
      ig: 'London',
      zu: 'ILondon',
      co: 'Londra',
      ascii: 'London',
      sv: 'London',
      ff: 'London',
      qu: 'London',
      io: 'London',
      ce: 'Лондон',
      su: 'London',
      bs: 'London',
      ht: 'Lonn',
      so: 'London',
      mg: 'Lôndôna',
      te: 'లండన్',
      am: 'ለንደን',
      bm: 'London',
      sw: 'London',
      it: 'Londra',
      nv: 'Tooh Dineʼé Bikin Haalʼá',
      an: 'Londres',
      lo: 'ລອນດອນ',
      jv: 'London',
      gl: 'Londres',
      be: 'Лондан',
      hy: 'Լոնդոն',
      ar: 'لندن',
      is: 'London',
      sh: 'London',
      ug: 'لوندۇن',
      tt: 'Лондон',
      rm: 'Londra',
      sq: 'Londra',
      bi: 'London',
      gu: 'લંડન',
      pa: 'ਲੰਡਨ',
      he: 'לונדון',
      az: 'London',
      ny: 'London',
      ha: 'Landan',
      om: 'Landan',
      hi: 'लंदन',
      st: 'London',
      bh: 'लंदन',
      id: 'London',
      no: 'London',
      ru: 'Лондон',
      ga: 'Londain',
      ab: 'Лондон',
      cv: 'Лондон',
      wo: 'Londar',
      cy: 'Llundain',
      pt: 'Londres',
      eo: 'Londono',
      sk: 'Londýn',
      bo: 'ལོན་ཊོན།',
      tk: 'London',
      gv: 'Lunnin',
      sc: 'Londra',
      ms: 'London',
      yi: 'לאנדאן',
      ml: 'ലണ്ടൻ',
      si: 'ලන්ඩන්',
      nl: 'Londen',
      kv: 'Лондон',
      fi: 'Lontoo',
      ka: 'ლონდონი',
      vi: 'Luân Đôn',
      kn: 'ಲಂಡನ್',
      mk: 'Лондон',
      ko: '런던',
      sd: 'لنڊن'
    },
    lat: 51.5073219,
    lon: -0.1276474,
    country: 'GB',
    state: 'England'
  },
  {
    name: 'City of London',
    local_names: {
      ur: 'لندن شہر',
      uk: 'Лондонське Сіті',
      pt: 'Cidade de Londres',
      fr: 'Cité de Londres',
      hi: 'सिटी ऑफ़ लंदन',
      es: 'City de Londres',
      he: 'הסיטי של לונדון',
      zh: '倫敦市',
      en: 'City of London',
      ko: '시티 오브 런던',
      ru: 'Сити',
      lt: 'Londono Sitis'
    },
    lat: 51.5156177,
    lon: -0.0919983,
    country: 'GB',
    state: 'England'
  },
  {
    name: 'London',
    local_names: {
      ru: 'Лондон',
      ga: 'Londain',
      ja: 'ロンドン',
      en: 'London',
      el: 'Λόντον',
      ko: '런던',
      oj: 'Baketigweyaang',
      lv: 'Landona',
      be: 'Лондан',
      ar: 'لندن',
      ka: 'ლონდონი',
      yi: 'לאנדאן',
      lt: 'Londonas',
      hy: 'Լոնտոն',
      fr: 'London',
      ug: 'لوندۇن',
      bn: 'লন্ডন',
      iu: 'ᓚᓐᑕᓐ',
      th: 'ลอนดอน',
      he: 'לונדון',
      cr: 'ᓬᐊᐣᑕᐣ',
      fa: 'لندن'
    },
    lat: 42.9832406,
    lon: -81.243372,
    country: 'CA',
    state: 'Ontario'
  },
  {
    name: 'Chelsea',
    local_names: {
      ur: 'چیلسی، لندن',
      fa: 'چلسی',
      no: 'Chelsea',
      ko: '첼시',
      hi: 'चेल्सी, लंदन',
      ar: 'تشيلسي',
      da: 'Chelsea',
      eu: 'Chelsea',
      id: 'Chelsea, London',
      tr: 'Chelsea, Londra',
      ga: 'Chelsea',
      he: "צ'לסי",
      nl: 'Chelsea',
      sv: 'Chelsea, London',
      et: 'Chelsea',
      en: 'Chelsea',
      af: 'Chelsea, Londen',
      el: 'Τσέλσι',
      ru: 'Челси',
      it: 'Chelsea',
      hu: 'Chelsea',
      sk: 'Chelsea',
      vi: 'Chelsea, Luân Đôn',
      pl: 'Chelsea',
      sh: 'Chelsea, London',
      pt: 'Chelsea',
      de: 'Chelsea',
      az: 'Çelsi',
      fr: 'Chelsea',
      uk: 'Челсі',
      zh: '車路士',
      es: 'Chelsea',
      ja: 'チェルシー'
    },
    lat: 51.4875167,
    lon: -0.1687007,
    country: 'GB',
    state: 'England'
  },
  {
    name: 'London',
    lat: 37.1289771,
    lon: -84.0832646,
    country: 'US',
    state: 'Kentucky'
  }
];
